Ketho/vscode-wow-api

EmmyLua/FrameXML/MapUtil.lua, EmmyLua/SharedXML/Color.lua, EmmyLua/SharedXML/ColorUtil.lua, EmmyLua/SharedXML/EasingUtil.lua, EmmyLua/SharedXML/PixelUtil.lua, EmmyLua/SharedXML/TimeUtil.lua, EmmyLua/SharedXML/Vector2D.lua, EmmyLua/SharedXML/Vector3D.lua
Adds global objects, functions and methods from the following files:
- FrameXML/MapUtil.lua
- SharedXML/EasingUtil.lua
- SharedXML/PixelUtil.lua
- SharedXML/TimeUtil.lua
Adds more functions to SharedXML/ColorUtil.lua
Some notes:
1. There is a problem using links to site `www.townlong-yak.com` for objects. Links like `https://www.townlong-yak.com/framexml/go/{object}` seem to be supported only for functions and mixins. It doesn't work for everything else, including functions like `MapUtil.IsMapTypeZone()`
Therefore, in such cases, I've added a link to file in which a given object is defined. Example: `https://www.townlong-yak.com/framexml/live/MapUtil.lua`
2. There is currently no StatusBar as a widget type. The last function in PixelUtil.lua file is commented out.
3. I suggest the …
=> Add to FrameXML

EmmyLua/API/SharedXML/Backdrop.lua
I noticed when a frame is created with the BackdropTemplateMixin all the backdrop items are not defined. This definition will allow the user to extend the frame class as needed to add in the proper doc info.
Before:
After:
The backdrop system does not have much documentation on Wowpedia outside of this one page https://wowpedia.fandom.com/wiki/BackdropTemplate I linked to it at the class level should I add links to it on each of the functions?
=> Add classes for frames using backdrops

.github/workflows/ReleaseBuilds.yml, .github/workflows/TestBuilds.yml
Contains 2 actions files. 
- ReleaseBuilds.yml will run on tag, and publish to VS Marketplace & Github Releases
- TestBuild.yml will just run a build on commit to verify build is functioning so if something breaks you know about it sooner than later.  
Looks like 0.8.0 was uploaded to the marketplace and nothing else was so you can delete the tags 0.8.1 and up and reuse the numbers. 
Screenshot from my repo of them working:
=> GH Action updates

EmmyLua/API/Libraries/Ace3/AceGUI-3.0/AceGUI-3.0.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-DropDownGroup.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-Frame.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-InlineGroup.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-SimpleGroup.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-Window.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Button.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-DropDown.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Heading.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Icon.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-InteractiveLabel.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Keybinding.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Label.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-MultiLineEditBox.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Slider.lua
As far as I can tell, there's no way of applying a prefix to the name of a generic for the return type, so I wasn't able to figure out any way of getting `AceGUI:Create` to return the proper widget type. It would need to prefix the first parameter with `AceGUI` and use that as the return type. Type definitions are included for all widgets for manual type casting.
=> Add AceGUI

EmmyLua/API/Libraries/LibStub/LibStub.lua
Currently, `LibStub:NewLibrary` has no return value. It now returns a value of generic type `T`.
Instead of having to manully specify a `@class` to the value, it's automatically inferred by whatever string is given as major. So: `LibStub:NewLibrary("MyLib-1.0")` returns a value of type `MyLib-1.0`.
=> Update `LibStub:NewLibrary` return value

EmmyLua/API/Libraries/LibDBIcon-1.0/LibDBIcon-1.0.lua
I was getting warnings on the functions if there was no return, so I put some blank returns
Then I moved all the return & input type classes to the bottom to try and fix the error you were seeing as noted in https://github.com/Ketho/vscode-wow-api/pull/55
=> LibDBIcon organize and move all return & input type classes to bottom

EmmyLua/API/Libraries/Ace3/AceConfig-3.0.lua
Add string as an acceptable input for get and set in AceConfigOptionsTable
=> Fix warning on AceConfigOptionsTable get and set

EmmyLua/API/Libraries/Ace3/AceDBOptions-3.0.lua
The type was manually renamed in another PR.
=> Fix return type for AceDBOptions:GetOptionsTable

EmmyLua/API/Libraries/Ace3/AceTab-3.0.lua
Add type definitions for AceTab-3.0 - this is a best effort, as the library has no public API docs and the code itself isn't as well documented as the other Ace3 libraries.
=> Add type definitions for AceTab-3.0

EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua, EmmyLua/API/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-MultiLineEditBox.lua
Per the documentation on those functions:
> Highlight the text in the editbox (see Blizzard EditBox Widget documentation for details)
From https://wowpedia.fandom.com/wiki/API_EditBox_HighlightText
> Leaving out both parameters, as in `EditBox:HighlightText()`, will highlight the entire EditBox content.
=> Make AceGUI HighlighText parameters optional

src/extension.ts
`Lua.workspace.library` was being updated but immediately overwritten on the second call to `setExternalLibrary`. After some debugging, it seems like `vscode.workspace.getConfiguration` does not reload everything from the config on the second time it is called.
There is some interesting magic going on here: https://github.com/microsoft/vscode/blob/230a6266ebc8e092521a949ed159d8be23e1b1b2/src/vs/workbench/api/common/extHostConfiguration.ts#L186
Related to issue #100 - please review with scrutiny, as I am not an experienced extension developer..
=> Update array before updating config

EmmyLua/API/Type/Type.lua
The classfile type seems to have gotten a bit out-of-sync with the Wiki; https://warcraft.wiki.gg/wiki/ClassId lists "EVOKER" but the extension doesn't.
=> Add Evoker to classfile union

EmmyLua/API/Type/BlizzardType.lua
The fileID type should probably be an integer under the hood, as that's what the API _really_ uses for both return values and structure fields.
There's a chance this might break some stuff - specifically, I'm wondering if we've documented some API parameters as being "fileIDs" when in fact they can be either a file ID or a file name.
=> File IDs are integers

EmmyLua/API/Libraries/Ace3/AceConfig-3.0/AceConfig-3.0.lua, EmmyLua/API/Libraries/Ace3/AceDB-3.0.lua
childGroups is optional when defining a group and should be marked as such.
=> Make childGroups optional in AceConfig.OptionsTable

Lua/Util/Util.lua
Looks like it returns a string error message, not an HTTP code.
=> Fix error when handling an HTTP error

EmmyLua/API/GlobalAPI/API4.lua
The former until about 5 minutes ago didn't have an API page at all, and the latter seems to be missing its varargs despite the wiki page listing them.
=> Update scrub and secureexecuterange

package.json, src/extension.ts
This option controls whether the extension attempts to automatically manage the diagnostics.globals setting.
=> Add option autoAddGlobals

Annotations/Libraries/Ace3/AceConfig-3.0/AceConfig-3.0.lua
This field being optional causes things that don't need args table to toss warnings.
=> Updated definition for Ace3 OptionsTable, args to be an optional

Annotations/Libraries/Ace3/AceGUI-3.0/AceGUI-3.0.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-BlizOptionsGroup.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-DropDownGroup.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-Frame.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-InlineGroup.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-SimpleGroup.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIContainer-Window.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Button.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-DropDown.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Heading.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Icon.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-InteractiveLabel.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Keybinding.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Label.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-MultiLineEditBox.lua, Annotations/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Slider.lua
* Add the `Table` layout as a valid `AceGUILayoutType`
* Add BlizOptionsGroup
* Add `@protected` fields and functions to all AceGUI widgets and containers, these will not show up in auto-completion suggestions unless you're working on a `@class` that inherits from a widget.
=> Update AceGUI documentation

Annotations/Libraries/Ace3/AceComm-3.0.lua
I think the `OnReceiveMultipartFirst`, `OnReceiveMultipartNext`, `OnReceiveMultipartLast` are correct to be defined as `@protected`, but I'm not entirely sure
=> Update AceComm documentation

.gitignore
`bin/setup.sh` puts the hererocks install in `.lua`, so that should be gitignored
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Ketho/vscode-wow-api/pull/167).
* #169
* #168
* __->__ #167
=> [1/3] add .lua to .gitignore

.gitignore, LuaScripts/WowDocLoader/Fixes.lua, LuaScripts/WowDocLoader/Loader.lua
`LuaScripts/main.lua` is failing to run because the fixes for the missing `PetConsts` values doesn't work with the current set of downloaded files.
This diff fixes the monkey-patching by:
- Running it during the invocation of `Loader:main()` instead of during the loading of `Loader.lua`. This reduces the risk of the fixes being overwritten by something else.
- Making it add missing values per-key instead of doing all-or-nothing on `PetConsts`. This was a problem because the most recent version of `LuaEnum.lua` includes `PetConsts`, but is missing some keys that are referenced in the docs.
After this fix, I was able to successfully run `LuaScripts/main.lua` and the results of that run are the next diff in this stack.
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with …
=> [2/3] monkey-patch PetConsts correctly

Annotations/Lua/string.lua
This matches the behavior in-game:
=> Update string.join arguments

Annotations/Interface/Blizzard_Menu/Proxies/SharedMenuDescriptionProxy.lua
now correctly identifies `i` and `elementDescription` in `for i, elementDescription in rootDescription:EnumerateElementDescriptions() do`
=> Fix SharedMenuDescriptionProxy:EnumerateElementDescriptions()

Annotations/Interface/Blizzard_Menu/Proxies/SharedMenuDescriptionProxy.lua
text-only menu items are added by adding a button without a callback
=> callback is optional in SharedMenuDescriptionProxy:CreateButton
